######################################################################
#
# File name : RotaryEncoder_tb_simulate.do
# Created on: Sun Jan 07 16:48:05 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L unisims_ver -L unimacro_ver -L secureip -L xil_defaultlib -lib xil_defaultlib xil_defaultlib.RotaryEncoder_tb xil_defaultlib.glbl

do {RotaryEncoder_tb_wave.do}

view wave
view structure
view signals

do {RotaryEncoder_tb.udo}

run 1000ns
