######################################################################
#
# File name : RotaryEncoder_tb.udo
# Created on: Sun Jan 07 16:41:54 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
