######################################################################
#
# File name : RotaryEncoder_tb_wave.do
# Created on: Sun Jan 07 16:41:54 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
