######################################################################
#
# File name : RotaryEncoder_tb_compile.do
# Created on: Sun Jan 07 16:48:01 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
C:\\modeltech_pe_10.4c\\win32pe\\vlib work
C:\\modeltech_pe_10.4c\\win32pe\\vlib msim

C:\\modeltech_pe_10.4c\\win32pe\\vlib msim/xil_defaultlib

C:\\modeltech_pe_10.4c\\win32pe\\vmap xil_defaultlib msim/xil_defaultlib

C:\\modeltech_pe_10.4c\\win32pe\\vlog -64 -incr -work xil_defaultlib  \
"../../../RotationSensor.srcs/sources_1/new/RotationSensor.v" \
"../../../RotationSensor.srcs/sim_1/new/RotationSensor_tb.v" \


# compile glbl module
C:\\modeltech_pe_10.4c\\win32pe\\vlog -work xil_defaultlib "glbl.v"

quit -force

