# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/Program/vivado/SteinsGate0_GIT/CentralGate/CentralGate.srcs/sources_1/ip/satellite1_rom/satellite1_rom.xci
# IP: The module: 'satellite1_rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Program/vivado/SteinsGate0_GIT/CentralGate/CentralGate.srcs/sources_1/ip/satellite1_rom/satellite1_rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'satellite1_rom'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: D:/Program/vivado/SteinsGate0_GIT/CentralGate/CentralGate.srcs/sources_1/ip/satellite1_rom/satellite1_rom.xci
# IP: The module: 'satellite1_rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Program/vivado/SteinsGate0_GIT/CentralGate/CentralGate.srcs/sources_1/ip/satellite1_rom/satellite1_rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'satellite1_rom'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
