######################################################################
#
# File name : Gate_ctrl_tb.udo
# Created on: Sat Jan 13 16:45:31 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
