# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: D:/Program/vivado/SteinsGate0_GIT/SteinsGate0/SteinsGate0.srcs/constraints/gate0_test.xdc

# IP: D:/Program/vivado/SteinsGate0_GIT/CentralGate/CentralGate.srcs/sources_1/ip/chara1_rom/chara1_rom.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==chara1_rom || ORIG_REF_NAME==chara1_rom}]

# IP: D:/Program/vivado/SteinsGate0_GIT/CentralGate/CentralGate.srcs/sources_1/ip/building2_rom/building2_rom.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==building2_rom || ORIG_REF_NAME==building2_rom}]

# IP: D:/Program/vivado/SteinsGate0_GIT/CentralGate/CentralGate.srcs/sources_1/ip/building1_rom/building1_rom.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==building1_rom || ORIG_REF_NAME==building1_rom}]

# IP: D:/Program/vivado/SteinsGate0_GIT/CentralGate/CentralGate.srcs/sources_1/ip/road1_rom/road1_rom.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==road1_rom || ORIG_REF_NAME==road1_rom}]

# IP: D:/Program/vivado/SteinsGate0_GIT/CentralGate/CentralGate.srcs/sources_1/ip/chris1_rom/chris1_rom.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==chris1_rom || ORIG_REF_NAME==chris1_rom}]

# IP: D:/Program/vivado/SteinsGate0_GIT/CentralGate/CentralGate.srcs/sources_1/ip/chara2_rom/chara2_rom.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==chara2_rom || ORIG_REF_NAME==chara2_rom}]

# IP: D:/Program/vivado/SteinsGate0_GIT/CentralGate/CentralGate.srcs/sources_1/ip/satellite1_rom/satellite1_rom.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==satellite1_rom || ORIG_REF_NAME==satellite1_rom}]

# IP: D:/Program/vivado/SteinsGate0_GIT/CentralGate/CentralGate.srcs/sources_1/ip/chris2_rom/chris2_rom.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==chris2_rom || ORIG_REF_NAME==chris2_rom}]
