######################################################################
#
# File name : Gate_logic_tb_compile.do
# Created on: Sun Jan 14 00:17:29 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
C:\\modeltech_pe_10.4c\\win32pe\\vlib work
C:\\modeltech_pe_10.4c\\win32pe\\vlib msim

C:\\modeltech_pe_10.4c\\win32pe\\vlib msim/xil_defaultlib
C:\\modeltech_pe_10.4c\\win32pe\\vlib msim/xpm

C:\\modeltech_pe_10.4c\\win32pe\\vmap xil_defaultlib msim/xil_defaultlib
C:\\modeltech_pe_10.4c\\win32pe\\vmap xpm msim/xpm

C:\\modeltech_pe_10.4c\\win32pe\\vlog -64 -incr -sv -work xil_defaultlib  \
"C:/Xilinx/Vivado/2016.2/data/ip/xpm/xpm_memory/hdl/xpm_memory_base.sv" \
"C:/Xilinx/Vivado/2016.2/data/ip/xpm/xpm_memory/hdl/xpm_memory_dpdistram.sv" \
"C:/Xilinx/Vivado/2016.2/data/ip/xpm/xpm_memory/hdl/xpm_memory_dprom.sv" \
"C:/Xilinx/Vivado/2016.2/data/ip/xpm/xpm_memory/hdl/xpm_memory_sdpram.sv" \
"C:/Xilinx/Vivado/2016.2/data/ip/xpm/xpm_memory/hdl/xpm_memory_spram.sv" \
"C:/Xilinx/Vivado/2016.2/data/ip/xpm/xpm_memory/hdl/xpm_memory_sprom.sv" \
"C:/Xilinx/Vivado/2016.2/data/ip/xpm/xpm_memory/hdl/xpm_memory_tdpram.sv" \

C:\\modeltech_pe_10.4c\\win32pe\\vcom -64 -93 -work xpm  \
"C:/Xilinx/Vivado/2016.2/data/ip/xpm/xpm_VCOMP.vhd" \

C:\\modeltech_pe_10.4c\\win32pe\\vlog -64 -incr -work xil_defaultlib  \
"../../../CentralGate.srcs/sources_1/new/Gate_logic.v" \
"../../../CentralGate.srcs/sim_1/new/Gate_logic_tb.v" \

# compile glbl module
C:\\modeltech_pe_10.4c\\win32pe\\vlog -work xil_defaultlib "glbl.v"

quit -force

