######################################################################
#
# File name : Gate_logic_tb_wave.do
# Created on: Tue Dec 26 16:54:49 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
