######################################################################
#
# File name : Gate_logic_tb_compile.do
# Created on: Tue Dec 26 21:53:27 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
C:\\modeltech_pe_10.4c\\win32pe\\vlib work
C:\\modeltech_pe_10.4c\\win32pe\\vlib msim

C:\\modeltech_pe_10.4c\\win32pe\\vlib msim/xil_defaultlib

C:\\modeltech_pe_10.4c\\win32pe\\vmap xil_defaultlib msim/xil_defaultlib

C:\\modeltech_pe_10.4c\\win32pe\\vlog -64 -incr -work xil_defaultlib  \
"../../../CentralGate.srcs/sources_1/new/Gate_logic.v" \
"../../../CentralGate.srcs/sim_1/new/Gate_logic_tb.v" \


# compile glbl module
C:\\modeltech_pe_10.4c\\win32pe\\vlog -work xil_defaultlib "glbl.v"

quit -force

