######################################################################
#
# File name : vga_test_tb_compile.do
# Created on: Mon Dec 25 19:24:37 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
C:\\modeltech_pe_10.4c\\win32pe\\vlib work
C:\\modeltech_pe_10.4c\\win32pe\\vlib msim

C:\\modeltech_pe_10.4c\\win32pe\\vlib msim/xil_defaultlib

C:\\modeltech_pe_10.4c\\win32pe\\vmap xil_defaultlib msim/xil_defaultlib

C:\\modeltech_pe_10.4c\\win32pe\\vlog -64 -incr -work xil_defaultlib  \
"../../../VGA.srcs/sources_1/new/VGA_color_syn.v" \
"../../../VGA.srcs/sources_1/new/divider.v" \
"../../../VGA.srcs/sources_1/new/vga_driver_640x480.v" \
"../../../VGA.srcs/sources_1/new/vga_test.v" \
"../../../VGA.srcs/sim_1/new/vga_test_tb.v" \


# compile glbl module
C:\\modeltech_pe_10.4c\\win32pe\\vlog -work xil_defaultlib "glbl.v"

quit -force

