######################################################################
#
# File name : vga_test_tb_wave.do
# Created on: Mon Dec 25 19:23:34 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
