# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_param simulator.modelsimInstallPath C:/modeltech_pe_10.4c/win32pe
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/Program/vivado/SteinsGate0_GIT/RotationSensor/RotationSensor.cache/wt [current_project]
set_property parent.project_path D:/Program/vivado/SteinsGate0_GIT/RotationSensor/RotationSensor.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib D:/Program/vivado/SteinsGate0_GIT/RotationSensor/RotationSensor.srcs/sources_1/new/RotationSensor.v
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/Program/vivado/SteinsGate0_GIT/RotationSensor/RotationSensor.srcs/constrs_1/new/RotationSensor.xdc
set_property used_in_implementation false [get_files D:/Program/vivado/SteinsGate0_GIT/RotationSensor/RotationSensor.srcs/constrs_1/new/RotationSensor.xdc]


synth_design -top RotaryEncoder -part xc7a100tcsg324-1


write_checkpoint -force -noxdef RotaryEncoder.dcp

catch { report_utilization -file RotaryEncoder_utilization_synth.rpt -pb RotaryEncoder_utilization_synth.pb }
