######################################################################
#
# File name : VGA_driver_tb.udo
# Created on: Sat Dec 23 12:57:16 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
